name: "Build & create NuGet"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.x']

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
      
      - name: Set project versions
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.2
        with:
          file: |
            "**/*.csproj"
          version: ${{ steps.version.outputs.version }}

      - name: Commit version changes
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git add .
          git commit -m "[skip ci] Update project versions to ${{ steps.update.outputs.newVersion }}"
          git push

